/**
 * Preprocesses markdown and LaTeX generated by LLMs to normalize:
 * 1. LaTeX display math \[ ... \] to $$ ... $$
 * 2. LaTeX inline math \( ... \) to $ ... $
 * 3. Accidental broken line breaks inside bold/italic markers
 */
export function normalizeMarkdownAndLatex(raw: string): string {
  if (!raw) return ''

  let text = raw

  // 1. Convert \[ ... \] to $$ ... $$
  text = text.replace(/\\\[([\s\S]*?)\\\]/g, (_, math) => `$$\n${math.trim()}\n$$`)

  // 2. Convert \( ... \) to $ ... $
  text = text.replace(/\\\(([\s\S]*?)\\\)/g, (_, math) => `$${math.trim()}$`)

  // 3. Fix broken bold wraps like **text \n** -> **text** \n
  text = text.replace(/\*\*([^*\n]+)\s*\n\s*\*\*/g, '**$1**\n')

  return text
}
